Miscellaneous warnings
input-leap/input-leap pull request #1447
Opened 2022-02-14 09:10 UTC by mokibit

This PR fixes miscellaneous warnings and deletes dead code. 

* [not needed] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

2022-02-14 11:54 UTC, shymega commented
This is failing, so we need to review this further.

2022-02-17 17:41 UTC, shymega commented
OK, good progress - now we just need to fix Windows builds..

2022-02-17 17:50 UTC, mokibit commented
@p12tic tests are fixed.

2022-02-17 17:54 UTC, p12tic requested changes
Found just a single small issue.

2022-02-17 19:12 UTC, shymega commented on src/test/global/gmock.h
> +#pragma GCC diagnostic push
OK, so this has been deleted from the PR, so I suppose this review could be reviewed, but I'd like to be sure it was intentional - @mokibit, could you confirm? Thank you!

2022-02-18 08:44 UTC, mokibit commented on src/test/global/gmock.h
> +#pragma GCC diagnostic push
@shymega, yes I fixed this.

2022-02-18 10:59 UTC, p12tic approved these changes

2022-02-18 10:59 UTC, merged

2022-02-18 18:00 UTC, shymega commented on src/test/global/gmock.h
> +#pragma GCC diagnostic push
@mokibit Awesome wanted to check before I could merge, but Povilas beat me to it 😅!