Updates for macOS Ventura on Apple Silicon with Qt6
input-leap/input-leap pull request #1653
Opened 2023-05-24 03:27 UTC by sigmahour

This contribution includes several changes I made while experimenting with input-leap on Apple Silicon. I addressed all the build warnings for both Apple and Intel Macs. The project now successfully works with qt6 installed via homebrew.

System Details:

    Operating System: macOS Ventura 13.4
    macOS SDK: 13.3
    QT Version: 6.5.0 (installed via homebrew)

The build does require a few steps in order to run without instantly crashing:

1. Create a symbolic link to the brotli common library from the homebrew installation. Here is the command I used:

```
ln -s /opt/homebrew/lib/libbrotlicommon.1.dylib /Applications/InputLeap.app/Contents/Frameworks/libbrotlicommon.1.dylib
```

2. Sign it:

```
codesign --force --deep --sign - /Applications/InputLeap.app
```

3. Enable in Accessibility:

Navigate to: `System Settings > Privacy & Security > Accessibility`
Remove and Re-add "InputLeap" using the "-" and "+" buttons at the bottom.

---

You can specify the version of Qt to build by setting the environment variable `QT_VERSION=5` or `QT_VERSION=6`. Default is set to version 6.

2023-05-24 14:16 UTC, shymega commented
I know someone managed to get a 'tap' working with macOS on Apple Sillicon. Maybe that'll help figure out the issue?

Also, all CI seems to have failed, so unfortunately, we can't merge this. The CI to pay attention to is GitHub Actions - not Azure Pipelines.

With regards to the commits, it looks sane, but I'd like, before merging when CI passes, it's all squashed into one commit.

2023-05-24 14:24 UTC, p12tic commented on clean_build.sh
> +        B_CMAKE_FLAGS="${B_CMAKE_FLAGS} -DCMAKE_OSX_SYSROOT=$(xcode-select --print-path)/SDKs/MacOSX.sdk -DCMAKE_OSX_DEPLOYMENT_TARGET=13.3"
This makes Barrier unusable on anything prior to 13.3

2023-05-24 14:24 UTC, p12tic commented on macos_environment.sh
> +        check_dir_exists '/opt/local/lib/cmake/Qt6' 'qt6-qtbase port'
This should be configurable

2023-05-25 04:06 UTC, vancluever commented
> I know someone managed to get a 'tap' working with macOS on Apple Silicon. Maybe that'll help figure out the issue.

@shymega that was me :slightly_smiling_face: and the homebrew tap is here: https://github.com/vancluever/homebrew-input-leap

Also mentioned in the forums [here](https://github.com/input-leap/input-leap/discussions/1623) and [here](https://github.com/input-leap/input-leap/discussions/1517#discussioncomment-5298379).

The tap is currently pinned to my fork while I wait for #1640.

Cheers!

2023-05-25 20:40 UTC, shymega requested changes
This should, ideally, be in a separate PR.

2023-05-26 14:31 UTC, shymega commented
You must have misunderstood me. I was referring specifically to the lines I referenced in my review.

2023-06-01 04:24 UTC, closed without merging

2023-06-02 20:40 UTC, shymega commented
Sorry, got busy with interviews.

I meant specifically the part I reviewed. There were (are?) some changes that didn't belong in this PR, but other parts did. The PR is still welcome, just split in sensible PRs.