ei: start with an initial screen size of 1920x1080
input-leap/input-leap pull request #1866
Opened 2024-02-22 05:08 UTC by whot

getShape() is called as soon as we connect to the server but at this point we do not have a shape yet, we're still waiting for the user to confirm the portal request. If we return all zeroes here the server disconnects us (ClientProxy1_6::recvInfo()), resulting in a continuous connect/disconnect loop until the user finally says yes.

Send an intial screen shape instead, that shape will get updated later when we get the devices through libei.

Fixes #1718

cc @Shuna322, can you give this a try please?

## Contributor Checklist:

* [ ] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

2024-02-22 07:40 UTC, sithlord48 commented
Why not use something like 1x1 for use size until we know. It should be enough to avoid the auto close from 0 size.

2024-02-22 08:03 UTC, whot commented
good point. I picked 1920x1080 because it's common enough and if the other side starts setting up something it'll be close to the final result. Not sure that'll ever happen, so 1x1 is probably just as well.

2024-02-22 17:56 UTC, p12tic requested changes
LGTM, but let's pick 1x1. Thanks a lot!

2024-02-26 07:18 UTC, whot commented
> LGTM, but let's pick 1x1. Thanks a lot!

done! thanks for the review!

2024-02-26 14:46 UTC, p12tic approved these changes

2024-02-26 14:46 UTC, merged