fix: stuck keys on client
input-leap/input-leap pull request #1972
Opened 2024-09-17 13:20 UTC by sithlord48

## Contributor Checklist:

* [ ] This is a user-visible change and I have created a file in the `doc/newsfragments` directory (and made sure to read the `README.md` in that directory)
* [X] This is not a user-visible change

this fixes keys being stuck when entering the client 
based on https://github.com/enzious/deskflow/tree/fix/stuck-keys-on-leave by @enzious

2024-09-17 13:57 UTC, Koston-0xDEADBEEF commented
Related:

https://github.com/input-leap/input-leap/issues/1690
https://github.com/input-leap/input-leap/issues/1896
https://github.com/input-leap/input-leap/issues/1897

2024-09-17 14:24 UTC, Koston-0xDEADBEEF commented
Patch tested to work on input-leap server, X11 (Xorg 7.7) on FreeBSD/amd64 (13.4-REL).

2024-09-18 15:48 UTC, Koston-0xDEADBEEF commented
Previously mentioned FreeBSD build tested against latest patch revision.

2024-09-19 07:21 UTC, Koston-0xDEADBEEF approved these changes
Excellent work.

2024-09-20 12:00 UTC, Koston-0xDEADBEEF requested changes
On further testing, this looks like it's causing the cursor move from server to client become laggy, cursor gets stuck on the server side screen for a moment before switching over to the client screen.

2024-09-20 13:42 UTC, sithlord48 commented
> On further testing, this looks like it's causing the cursor move from server to client become laggy, cursor gets stuck on the server side screen for a moment before switching over to the client screen.

I didn't see any change is cursor time to leave // enter screen when testing this on X11 / Wayland servers. odd

2024-09-25 11:04 UTC, Koston-0xDEADBEEF commented
> > On further testing, this looks like it's causing the cursor move from server to client become laggy, cursor gets stuck on the server side screen for a moment before switching over to the client screen.
> 
> I didn't see any change is cursor time to leave // enter screen when testing this on X11 / Wayland servers. odd , Hopefully we can get some additional testing here and figure out where your new lag is coming from

Tested again with intent to debug further, and was unable to reproduce the problem anymore. It must've been something unrelated that just unluckily coincided with testing this patch. Sorry for the noise and trouble.

2024-09-28 18:04 UTC, p12tic commented on src/lib/platform/MSWindowsScreen.cpp
> +    // unable to get position this means deskflow will break if the cursor
Wrong name of the project.

2024-09-29 02:12 UTC, sithlord48 commented on src/lib/platform/MSWindowsScreen.cpp
> +    // unable to get position this means deskflow will break if the cursor
Fixed

2024-09-29 15:23 UTC, shymega commented
@p12tic Please re-review, PR has been updated.

2024-09-29 15:24 UTC, shymega commented
Rebased against master.

2024-09-29 16:00 UTC, p12tic commented
The following should be somewhere in the extended commit description `This fixes keys being stuck when entering the client`.

Also, is this really not a user-visible change? It fixes several bug reports, so almost by definition it's user-visible change...

2024-09-29 16:08 UTC, sithlord48 commented
it does not change anything the user sees so in that respect no its not user visible.

I can't update the commit message right now feel free to include that as a second line in the commit message

2024-09-29 16:10 UTC, p12tic commented
> it does not change anything the user sees so in that respect no its not user visible.

Fair. I think the PR template needs to be changed then. "User-visible" was intended to mean "has impact to the end users".

2024-09-29 16:12 UTC, sithlord48 commented
> > it does not change anything the user sees so in that respect no its not user visible.
> 
> Fair. I think the PR template needs to be changed then. "User-visible" was intended to mean "has impact to the end users".

I think the whole manual tracking is a waste of time if we use proper commit message prefixes.. release notes are automatic.

2024-09-29 16:17 UTC, p12tic commented
> I think the whole manual tracking is a waste of time if we use proper commit message prefixes.. release notes are automatic.

Well, release notes are for humans to read. It always requires human review - to highlight things that are important, combine similar release notes into one and so on.

2024-09-29 16:33 UTC, sithlord48 commented
> > I think the whole manual tracking is a waste of time if we use proper commit message prefixes.. release notes are automatic.
> 
> Well, release notes are for humans to read. It always requires human review - to highlight things that are important, combine similar release notes into one and so on.

Again with proper commit messages its amazing how well the auto notes come out . They show right on the release page no need to add a file to the package or waste time adding them into some dialog or list . its literally on the release and whats better is you can as a viewer have it on the fly show you the changes for any release to another. They also link to the PR they belong to so you can read the description of that if you really care about some specific change

2024-09-30 19:55 UTC, Koston-0xDEADBEEF approved these changes
LGTM

2024-10-01 21:17 UTC, merged